import { Link } from 'react-router-dom'
import { sx } from '../lib/sx'
import { ROUTES } from '../lib/routes'

const CSS = `
a{color:#3448A8}a:hover{color:#0D1D41}
`

export default function Flujo() {
  return (
    <>
      <style>{CSS}</style>
      <div style={sx("position: relative; width: 2000px; height: 940px; background: #F6F7F9; font-family: 'Montserrat', system-ui, sans-serif; color: #0D1D41")}>
      <svg width="79" height="8" viewBox="0 0 79 8" preserveAspectRatio="none" style={sx("position: absolute; left: 304px; top: 304px; width: 79px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-1" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 0 4 L 75 4" markerEnd="url(#dc-arrow-head-filled-1)"></path></svg>
      <svg width="79" height="8" viewBox="0 0 79 8" preserveAspectRatio="none" style={sx("position: absolute; left: 624px; top: 304px; width: 79px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-2" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 0 4 L 75 4" markerEnd="url(#dc-arrow-head-filled-2)"></path></svg>
      <svg width="79" height="8" viewBox="0 0 79 8" preserveAspectRatio="none" style={sx("position: absolute; left: 944px; top: 304px; width: 79px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-3" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 0 4 L 75 4" markerEnd="url(#dc-arrow-head-filled-3)"></path></svg>
      <svg width="79" height="8" viewBox="0 0 79 8" preserveAspectRatio="none" style={sx("position: absolute; left: 1264px; top: 304px; width: 79px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-4" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 0 4 L 75 4" markerEnd="url(#dc-arrow-head-filled-4)"></path></svg>
      <svg width="79" height="8" viewBox="0 0 79 8" preserveAspectRatio="none" style={sx("position: absolute; left: 1584px; top: 304px; width: 79px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-5" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 0 4 L 75 4" markerEnd="url(#dc-arrow-head-filled-5)"></path></svg>
      <svg width="8" height="103" viewBox="0 0 8 103" preserveAspectRatio="none" style={sx("position: absolute; left: 500px; top: 376px; width: 8px; height: 103px; overflow: visible; fill: none; stroke: #8A95A3; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; stroke-dasharray: 6 6")}><defs><marker id="dc-arrow-head-filled-6" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#8A95A3" stroke="none" style={sx("stroke: none; fill: #8A95A3; fill: context-stroke")}/></marker></defs><path d="M 4 0 L 4 99" markerEnd="url(#dc-arrow-head-filled-6)"></path></svg>
      <svg width="8" height="103" viewBox="0 0 8 103" preserveAspectRatio="none" style={sx("position: absolute; left: 820px; top: 377px; width: 8px; height: 103px; overflow: visible; fill: none; stroke: #8A95A3; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; stroke-dasharray: 6 6")}><defs><marker id="dc-arrow-head-filled-7" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#8A95A3" stroke="none" style={sx("stroke: none; fill: #8A95A3; fill: context-stroke")}/></marker></defs><path d="M 4 103 L 4 4" markerEnd="url(#dc-arrow-head-filled-7)"></path></svg>
      <svg width="8" height="103" viewBox="0 0 8 103" preserveAspectRatio="none" style={sx("position: absolute; left: 1140px; top: 377px; width: 8px; height: 103px; overflow: visible; fill: none; stroke: #8A95A3; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; stroke-dasharray: 6 6")}><defs><marker id="dc-arrow-head-filled-8" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#8A95A3" stroke="none" style={sx("stroke: none; fill: #8A95A3; fill: context-stroke")}/></marker></defs><path d="M 4 103 L 4 4" markerEnd="url(#dc-arrow-head-filled-8)"></path></svg>
      <svg width="8" height="292" viewBox="0 0 8 292" preserveAspectRatio="none" style={sx("position: absolute; left: 1780px; top: 376px; width: 8px; height: 292px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><path d="M 4 0 L 4 292"></path></svg>
      <svg width="640" height="8" viewBox="0 0 640 8" preserveAspectRatio="none" style={sx("position: absolute; left: 1144px; top: 664px; width: 640px; height: 8px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><path d="M 0 4 L 640 4"></path></svg>
      <svg width="8" height="51" viewBox="0 0 8 51" preserveAspectRatio="none" style={sx("position: absolute; left: 1140px; top: 668px; width: 8px; height: 51px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-9" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 4 0 L 4 47" markerEnd="url(#dc-arrow-head-filled-9)"></path></svg>
      <svg width="8" height="51" viewBox="0 0 8 51" preserveAspectRatio="none" style={sx("position: absolute; left: 1460px; top: 668px; width: 8px; height: 51px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-10" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 4 0 L 4 47" markerEnd="url(#dc-arrow-head-filled-10)"></path></svg>
      <svg width="8" height="51" viewBox="0 0 8 51" preserveAspectRatio="none" style={sx("position: absolute; left: 1780px; top: 668px; width: 8px; height: 51px; overflow: visible; fill: none; stroke: #3448A8; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round")}><defs><marker id="dc-arrow-head-filled-11" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#3448A8" stroke="none" style={sx("stroke: none; fill: #3448A8; fill: context-stroke")}/></marker></defs><path d="M 4 0 L 4 47" markerEnd="url(#dc-arrow-head-filled-11)"></path></svg>
      <svg width="8" height="103" viewBox="0 0 8 103" preserveAspectRatio="none" style={sx("position: absolute; left: 180px; top: 377px; width: 8px; height: 103px; overflow: visible; fill: none; stroke: #8A95A3; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; stroke-dasharray: 6 6")}><defs><marker id="dc-arrow-head-filled-12" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#8A95A3" stroke="none" style={sx("stroke: none; fill: #8A95A3; fill: context-stroke")}/></marker></defs><path d="M 4 103 L 4 4" markerEnd="url(#dc-arrow-head-filled-12)"></path></svg>
      <svg width="8" height="103" viewBox="0 0 8 103" preserveAspectRatio="none" style={sx("position: absolute; left: 500px; top: 617px; width: 8px; height: 103px; overflow: visible; fill: none; stroke: #8A95A3; stroke-width: 2; stroke-linecap: round; stroke-linejoin: round; stroke-dasharray: 6 6")}><defs><marker id="dc-arrow-head-filled-13" orient="auto" markerWidth="5" markerHeight="5" refX="2" refY="2" overflow="visible"><path d="M0 0 L4 2 L0 4 Z" fill="#8A95A3" stroke="none" style={sx("stroke: none; fill: #8A95A3; fill: context-stroke")}/></marker></defs><path d="M 4 103 L 4 4" markerEnd="url(#dc-arrow-head-filled-13)"></path></svg>
      
      <div style={sx("position: absolute; left: 64px; top: 64px; font-family: 'Montserrat', sans-serif; font-size: 36px; font-weight: 600")}>Flujo completo del demo AI27</div>
      <div style={sx("position: absolute; left: 64px; top: 120px; width: 1100px; font-size: 16px; line-height: 24px; color: #5F6B7A")}>Guion de 15 a 20 minutos. Haz clic en cualquier paso para abrir su pantalla; dentro de cada pantalla, el botón principal te lleva al siguiente paso.</div>
      
      <Link to={ROUTES.Main} style={sx("position: absolute; left: 64px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 1</b><br /><b style={sx("font-size: 17px")}>Dashboard directivo</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Foto de la operación hoy y alertas priorizadas</span></span></Link>
      <Link to={ROUTES.Cotizador} style={sx("position: absolute; left: 384px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 2</b><br /><b style={sx("font-size: 17px")}>Cotizador</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Distancia, riesgo y margen; sale en PDF</span></span></Link>
      <Link to={ROUTES.AsignacionIA} style={sx("position: absolute; left: 704px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 3</b><br /><b style={sx("font-size: 17px")}>Asignación por IA</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>La IA recomienda custodios y unidad; el coordinador asigna</span></span></Link>
      <Link to={ROUTES.Monitoreo} style={sx("position: absolute; left: 1024px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 4</b><br /><b style={sx("font-size: 17px")}>Monitoreo en vivo</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Samsara dispara una alerta de desvío</span></span></Link>
      <Link to={ROUTES.Reaccion} style={sx("position: absolute; left: 1344px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 5</b><br /><b style={sx("font-size: 17px")}>Reacción</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Autoridades, equipo R-03 y recuperación</span></span></Link>
      <Link to={ROUTES.ReporteIncidente} style={sx("position: absolute; left: 1664px; top: 240px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-top: 4px solid #475CC7; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>PASO 6</b><br /><b style={sx("font-size: 17px")}>Reporte al cliente</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Cierre del incidente y envío a Alpura</span></span></Link>
      
      <Link to={ROUTES.Servicios} style={sx("position: absolute; left: 384px; top: 480px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px dashed #C3CBD5; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #5F6B7A")}>MÓDULO</b><br /><b style={sx("font-size: 17px")}>Servicios y bitácora</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Evento, dedicado o monitoreo</span></span></Link>
      <Link to={ROUTES.Custodios} style={sx("position: absolute; left: 704px; top: 480px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px dashed #C3CBD5; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #5F6B7A")}>MÓDULO</b><br /><b style={sx("font-size: 17px")}>Control de custodios</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Expedientes, estatus y turnos</span></span></Link>
      <Link to={ROUTES.CustodioMovil} style={sx("position: absolute; left: 1024px; top: 480px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px dashed #C3CBD5; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #5F6B7A")}>MÓVIL</b><br /><b style={sx("font-size: 17px")}>Vista custodio</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Check-in, evidencias y botón de pánico</span></span></Link>
      <Link to={ROUTES.AsistenteIA} style={sx("position: absolute; left: 64px; top: 480px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #F0F3FD; border: 1px dashed #B9C4EE; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>IA</b><br /><b style={sx("font-size: 17px")}>Asistente IA</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Preguntas en lenguaje natural con gráficas</span></span></Link>
      <Link to={ROUTES.CRM} style={sx("position: absolute; left: 384px; top: 720px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px dashed #C3CBD5; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #5F6B7A")}>MÓDULO</b><br /><b style={sx("font-size: 17px")}>Clientes y CRM</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Vista 360, contratos y pipeline</span></span></Link>
      
      <Link to={ROUTES.Flotilla} style={sx("position: absolute; left: 1024px; top: 720px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>VISTA RÁPIDA</b><br /><b style={sx("font-size: 17px")}>Flotilla y taller</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Unidades, órdenes y combustible</span></span></Link>
      <Link to={ROUTES.RH} style={sx("position: absolute; left: 1344px; top: 720px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>VISTA RÁPIDA</b><br /><b style={sx("font-size: 17px")}>Personas (RH)</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Toda la empresa: perfiles, altas y bajas</span></span></Link>
      <Link to={ROUTES.Finanzas} style={sx("position: absolute; left: 1664px; top: 720px; width: 240px; height: 136px; box-sizing: border-box; padding: 16px; display: flex; align-items: center; background: #FFFFFF; border: 1px solid #E4E8ED; border-radius: 12px; text-decoration: none; color: #0D1D41; line-height: 1.45")}><span><b style={sx("font-size: 12px; letter-spacing: .06em; color: #0D1D41")}>VISTA RÁPIDA</b><br /><b style={sx("font-size: 17px")}>Rentabilidad</b><br /><span style={sx("font-size: 14px; color: #5F6B7A")}>Margen por cliente, servicio y unidad</span></span></Link>
      
      <div style={sx("position: absolute; left: 516px; top: 420px; width: 172px; font-size: 13px; line-height: 16px; color: #5F6B7A")}>se convierte en servicio</div>
      <div style={sx("position: absolute; left: 836px; top: 420px; width: 180px; font-size: 13px; line-height: 16px; color: #5F6B7A")}>disponibilidad y expediente</div>
      <div style={sx("position: absolute; left: 1156px; top: 420px; width: 140px; font-size: 13px; line-height: 16px; color: #5F6B7A")}>check-ins y pánico</div>
      <div style={sx("position: absolute; left: 1569px; top: 640px; width: 110px; text-align: center; font-size: 13px; line-height: 16px; color: #0D1D41")}>vistas rápidas</div>
      
      <div style={sx("position: absolute; left: 196px; top: 420px; width: 150px; font-size: 13px; line-height: 16px; color: #5F6B7A")}>pregunta y grafica</div>
      <div style={sx("position: absolute; left: 516px; top: 660px; width: 190px; font-size: 13px; line-height: 16px; color: #5F6B7A")}>contratos y tarifas</div>
      <div style={sx("position: absolute; left: 64px; top: 720px; width: 280px; font-size: 14px; line-height: 22px; color: #3E4A59")}><b>Cómo leerlo.</b> Línea ámbar: ruta principal del guion. Línea punteada: módulos que alimentan un paso. Personas (RH) y Usuarios y roles están en el menú lateral.</div>
      </div>
    </>
  )
}
